### ISSUE TITLE
旋转目标检测

### ISSUE THREAD

**Issue by neuhsm** [bubbliiiing/yolov7-pytorch#82]
泡泡哥能出YOLOV7或者v7tiny的旋转目标检测代码吗，OBB那种，找到有人在你的代码的基础上改进成obb的 
 https://github.com/Egrt/yolov7-obb  https://github.com/Egrt/yolov7-tiny-obb ，但是需要安装一个非极大值抑制的库比较难，然后算map那块他没搞obb的map，当成hbb的来算的

**Comment by Egrt** [comment]
不安装非极大值抑制的库而用numpy计算会非常慢的
