### ISSUE TITLE
I want to ask about loading weights

### ISSUE THREAD

**Issue by VietPT3502** [bubbliiiing/yolov7-pytorch#89]
I have a trained yolov7 official weights in visDrone dataset. Can u load that weights in to your model? is there any thing i should notice ?

**Comment by bubbliiiing** [comment]
no, sorry, my name of  weights of the model in code is not same to official

**Comment by VietPT3502** [comment]
tks for the reply. I will close this

**Comment by VietPT3502** [comment]
but can you give me the drive to download the weight for training because i can't access baidu

**Comment by bubbliiiing** [comment]
look here https://github.com/bubbliiiing/yolov7-pytorch/releases/tag/v1.0
